version: "3"

services:
  node:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    command: ./docker/entrypoint.sh
    volumes:
      - ./:/app:${CONSISTENCY:-cached}
      - ./.config/:/root/.config:${CONSISTENCY:-cached}
    ports:
      - 5000:5000
      - 5001:5001
      - 9005:9005
