version: "3"

services:
  server:
    build:
      context: .
      dockerfile: ./functions/docker/Dockerfile.dev
    command: ./functions/docker/entrypoint.sh
    volumes:
      - ./:/app:${CONSISTENCY:-cached}
      - ./.config/:/root/.config:${CONSISTENCY:-cached}
    ports:
      - 5000:5000
      - 5001:5001
      - 9005:9005
  client:
    build:
      context: .
      dockerfile: ./client/docker/Dockerfile.dev
    environment:
      LOCAL_IP: ${LOCAL_IP:-0.0.0.0}
    command: ./docker/entrypoint.sh
    volumes:
      - ./client:/client:${CONSISTENCY:-cached}
    ports:
      - 8080:8080
      - 8081:8081
