version: "3"

services:
  server:
    build:
      context: .
      dockerfile: ./packages/server/docker/Dockerfile.dev
    command: ./docker/entrypoint.sh
    env_file:
      - .env
    volumes:
      - ./.firebaserc:/.firebaserc:${CONSISTENCY:-cached}
      - ./package.json:/package.json:${CONSISTENCY:-cached}
      - ./packages/shared:/packages/shared:${CONSISTENCY:-cached}
      - ./packages/server:/packages/server:${CONSISTENCY:-cached}
    ports:
      - 5000:5000
      - 5001:5001
      - 9005:9005
  client:
    build:
      context: .
      dockerfile: ./packages/client/docker/Dockerfile.dev
    command: ./docker/entrypoint.sh
    volumes:
      - ./package.json:/package.json:${CONSISTENCY:-cached}
      - ./packages/shared:/packages/shared:${CONSISTENCY:-cached}
      - ./packages/client:/packages/client:${CONSISTENCY:-cached}
    ports:
      - 8080:8080
      - 8081:8081
  deploy:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ./scripts/deploy.sh
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    env_file:
      - .env
